# Generated by Django 3.2.3 on 2021-05-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10)),
                ('question', models.CharField(max_length=100)),
                ('optionA', models.CharField(max_length=100)),
                ('optionB', models.CharField(max_length=100)),
                ('optionC', models.CharField(max_length=100)),
                ('optionD', models.CharField(max_length=100)),
                ('max_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qPaperTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('file_of_test', models.FileField(upload_to='tests', blank=True, null=True)),
                ('questions', models.ManyToManyField(to='exams.QuestionDB')),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('total_marks', models.IntegerField()),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.questionpaper')),
            ],
        ),
    ]
