# Generated by Django 3.2.3 on 2021-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_listening')),
                ('context', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Hard')], default=1)),
                ('title', models.CharField(max_length=31)),
            ],
        ),
    ]
