# Generated by Django 3.2.3 on 2021-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_listeningresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondb',
            name='max_marks',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='exams.QuestionDB'),
        ),
    ]
