# Generated by Django 3.2.3 on 2021-05-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20210526_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
        migrations.AddField(
            model_name='questiondb',
            name='test_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.questionpaper'),
        ),
    ]
