# Generated by Django 3.2.3 on 2021-05-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20210526_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionDB',
            new_name='Test',
        ),
        migrations.RenameModel(
            old_name='QuestionPaper',
            new_name='TestObject',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='question_paper',
            new_name='test_object',
        ),
        migrations.DeleteModel(
            name='ExamModel',
        ),
    ]
